httpsOnly: true # If you want enforce only HTTPS links
pullRequestReview: true # If you want a nice review in your pull requests
ignore: 
  urls: # Array of url to ignore
    - https://github.com
    - https://www.toptal.com/designers/htmlarrows/symbols/
    - https://svgconverter.app/
    - https://www.svgrepo.com/
    - https://pattern.monster/
  files: # Array of markdown file the shouldn't parse
    - ./test.md # Relative path from the folder shared above
delay:
  'https://gitlab.com': 500 # Perform a pause of 500ms at each call matching the url
